### ISSUE TITLE
Cannot set property 'inside' of undefined

### ISSUE THREAD

**Issue by tyrion** [survivejs/prism-languages#2]
This package is currently broken for me, and crashes when I try to require it
```
$ npm install 'prismjs@<2.0.0' prism-languages && node -e 'require("prism-languages")
npm WARN saveError ENOENT: no such file or directory, open '/home/tyrion/src/prova/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/tyrion/src/prova/package.json'
npm WARN prova No description
npm WARN prova No repository field.
npm WARN prova No README data
npm WARN prova No license field.

+ prism-languages@0.4.0
+ prismjs@1.17.1
updated 2 packages and audited 17 packages in 0.648s
found 0 vulnerabilities

/home/tyrion/src/prova/node_modules/prism-languages/index.js:560
        Prism.languages.django.script.inside.string.inside = _django_template;
                                                           ^

TypeError: Cannot set property 'inside' of undefined
    at Object.<anonymous> (/home/tyrion/src/prova/node_modules/prism-languages/index.js:560:53)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:122:20)
```

**Comment by bebraw** [comment]
I think the implementation of Prism has shifted and we have to rework this package. Maybe it's time to deprecate?
